source 'https://rubygems.org'
ruby '2.5.3'

gem 'activeadmin', '~> 2.9'
gem 'activemodel', '~> 5.2', '>= 5.2.2'
gem 'bootsnap'
gem 'bootstrap', '~> 4.6'
gem 'bootstrap-datepicker-rails', '~> 1.9', '>= 1.9.0.1'
gem 'browser'
gem 'coffee-rails', '~> 4.2', '>= 4.2.2'
gem 'devise', '~> 4.7'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'pg', '~> 1.1', '>= 1.1.4'
gem 'puma', '~> 5.2', '>= 5.2.1'
gem 'rails_12factor', group: 'production'
gem 'rails', '~> 5.2', '>= 5.2.4.3'
gem 'railties', '~> 5.2', '>= 5.2.4.3'
gem "rolify"
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 2.0', '>= 2.0.4'
gem 'simple_form', '~> 5.1'
gem 'spreadsheet'
gem 'stripe'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'listen'
  gem 'spring'
  gem 'web-console', '~> 3.7'
end

group :development, :test do
  gem 'byebug'
  gem 'factory_bot_rails', '~> 5.0'
  gem 'factory_bot'
  gem 'faker'
  gem 'pry-rails', '~> 0.3.4'
  gem 'rails-controller-testing'
  gem 'rspec-rails', '~> 3.8', '>= 3.8.2'
  gem 'shoulda-matchers', '~> 4.5', '>= 4.5.1'
  gem 'shoulda', '~> 4.0'
  gem 'timecop'
end
