development:
  adapter: postgresql
  encoding: unicode
  database: WEB_development
  pool: 5
  username: web
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: WEB_test
  pool: 5
  username: web
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: WEB_production
  pool: 5
  username: web
  password: password1
