# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605125d308f2a4fc9451a77574846a74ad5b30739deef1715eabc70849e85db3bcbbed8321126f4d18629b72c5ba7b4676dcb7005d85897bf96ff5d9ad218d6f

test:
  secret_key_base: cb21184fd69c3ee8c94a97f12275952be5c49269fbaf6464916c25f4fb453254aedf8320402a8d9e7941c95184b77766702b2482bac17961ee43dd68fd21e671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
